name: test mise

on:
  pull_request:
  push:
  schedule:
    - cron: 0 0 * * 5

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Mise
        uses: jdx/mise-action@v3
        with:
          install: false

      - run: mise exec asdf:https://github.com/younke/asdf-sourcery@latest -- sourcery --version
